assessments_main/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MechRevTest.views.home', name='home'),
    # url(r'^MechRevTest/', include('MechRevTest.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/?', include(admin.site.urls)),

    url(r'/?^$', 'users.views.splash', name='splash'),
    # url(r'^api/v1/?', include('assessments.urls', namespace='assessments')),
    # url(r'^touchstone/api/v1/?', include('assessments.urls', namespace='touchstone')),

    url(r'^api/v2/assessment/?', include('assessmentsv2.urls', namespace='assessmentsv2')),
    url(r'^touchstone/api/v2/assessment/?', include('assessmentsv2.urls', namespace='touchstonev2')),

    url(r'^api/v2/authorization/?', include('authorization.urls', namespace='authorization')),
    url(r'^touchstone/api/v2/authorization/?', include('authorization.urls', namespace='authorization_touchstone')),

    url(r'^api/v2/repository/?', include('repository.urls', namespace='repository')),
    url(r'^touchstone/api/v2/repository/?', include('repository.urls', namespace='repository_touchstone')),

    url(r'^api/v2/resource/?', include('resource.urls', namespace='resource')),
    url(r'^touchstone/api/v2/resource/?', include('resource.urls', namespace='resource_touchstone')),

    url(r'^api/v2/grading/?', include('grading.urls', namespace='grading')),
    url(r'^touchstone/api/v2/grading/?', include('grading.urls', namespace='grading_touchstone')),

    url(r'^api/v2/learning/?', include('learning.urls', namespace='learning')),
    url(r'^touchstone/api/v2/learning/?', include('learning.urls', namespace='learning_touchstone')),

    url(r'^api/v2/logging/?', include('logging_.urls', namespace='logging')),
    url(r'^touchstone/api/v2/logging/?', include('logging_.urls', namespace='logging_touchstone')),

    url(r'^users/?', include('users.urls', namespace='users')),
    url(r'^lti/?', include('lti.urls', namespace='lti')),
)

lti/urls.py
from django.conf.urls import patterns, url
from lti import views

urlpatterns = patterns('',
    url(r'^$',
        views.provider,
        name='provider'),
    url(r'^submit/$',
        views.check_response,
        name='check_response'),
    url(r'^retry/$',
        views.retry,
        name='retry'),
    url(r'^return/$',
        views.return_lms,
        name='return_lms'),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'^groups/$',
        views.groups,
        name='groups'),
    url(r'^login/$',
        views.login_user,
        name='login'),
    url(r'^manage/$',
        views.manage_users,
        name='manage_users'),
    url(r'^newkeys/$',
        views.regen_keys,
        name='regen_keys'),
    url(r'^oauth/$',
        views.oauth,
        name='oauth'),
    url(r'^oauth/(?P<consumer_id>[\d]+)/$',
        views.oauth_consumer,
        name='oauth_consumer'),
    url(r'^remove/$',
        views.remove,
        name='remove'),
    url(r'^splash/$',
        views.splash,
        name='splash'),
)

users/views.py
import pdb
import json
import logging

from django.core.cache import cache
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.views.decorators.cache import cache_page
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test

from django.utils.http import urlquote_plus

from oauth_provider.models import Consumer

from .utilities import *

@login_required
@user_passes_test(lambda u: u.is_staff)
def groups(request):
    """
    Requires that users are logged in via Touchstone--only way to get here
    request.method == 'POST', add user to group
    request.method == 'DELETE', remove user from that group
    """
    try:
        membership = Membership()
        results = {}
        if request.method == 'POST' and request.user.is_superuser:
            group_id = request.POST['groupId']
            set_staff = json.loads(request.POST['setStaff'])
            user_email = request.POST.get('username', request.user.username)
            if set_staff:
                role = 'Instructor'
            else:
                # "Student" roles can only be created by MITSIS, per error message
                # "Learner" roles need to be in the parent group, too
                role = 'Learner'
                # membership.add_user_to_assessments(user_email, role)
            if is_number(group_id):
                # group exists...add user in the service
                # first need to query for the user ID in Membership
                # then use that plus groupId
                new_group_id = group_id
                new_group_name = membership.group_name(new_group_id)
            else:
                # create child group with name = group_id, then add user
                (new_group_id, new_group_name) = membership.create_group(group_id)
            results['message'] = membership.add_user_to_group(user_email, new_group_id, role)
            results['groupName'] = new_group_name
            results['role'] = role
            results['groupId'] = new_group_id

            # set a flag for if the session user is the same as the proxied
            # user. Used to update the UI for user management
            if user_email == request.user.username:
                results['same_user'] = True
            else:
                results['same_user'] = False
        elif request.method == 'DELETE' and request.user.is_superuser:
            pass
        elif request.method == 'GET' and request.user.is_superuser:
            # get groups for a username, passed in as parameter
            username = request.GET.get('username', None)
            if username:
                results['groups'] = membership.user_groups(username, full=True)
            else:
                # return all groups
                results['groups'] = membership.all_groups()
        else:
            raise Exception('Invalid request / you are not authorized.')
    except Exception as ex:
        results['message'] = log_error('users.views.groups()', ex)
        results['success'] = False
    else:
        results['success'] = True
    finally:
        return HttpResponse(json.dumps(results), content_type='application/json')

def login_user(request):
    """
    Log in the user...only allow if is a superuser
    """
    username = request.POST['username']
    pwd = request.POST['password']
    redirect_url = request.POST.get('next', reverse('users:manage_users'))
    if redirect_url == '':
        redirect_url = '/users/manage/'  #reverse('users:manage_users')

    user = authenticate(username=username, password=pwd)
    if user is not None:
        if user.is_active:
            login(request, user)
            if user.is_authenticated() and user.is_superuser:
                return HttpResponseRedirect(redirect_url)
            else:
                state = "Login error."
                logging.info('User not authenticated: ' + username)
        else:
            state = "Your account is not active."
            logging.info('Not an active user: ' + username)
    else:
        state = "Incorrect username and/or password."
        logging.info('Incorrect username / password: ' + username)

    return render_to_response('users/splash.html',
                              {'state' : state,'next':redirect_url},
                              RequestContext(request))

@login_required
@user_passes_test(lambda u: u.is_staff)
def manage_users(request):
    """
    Requires that users are logged in via Touchstone--only way to get here
    Each regular user should see their groups and their public / private key
        * They should be able to change their public / private key
        * They can un-subscribe from a group
        * They can request access to a group (e-mail should be sent to superusers)
    Superusers should see their own public / private key (no one else's), all users,
        and each user's groups.
        * Should be able to add new users
        * Should be able to assign users to groups
        * Should be able to remove users from groups
    Use the IS&T Membership service for the groups part?
    """
    if request.user.is_superuser:
        all_users = json.dumps(get_all_users())
        # user_groups = json.dumps(membership.user_groups_mapping())
        user_groups = []
    else:
        all_users = []
        user_groups = []

    if request.user.public_key:
        my_public_key = request.user.public_key
    else:
        my_public_key = create_new_key(request.user, 'public')

    if request.user.private_key:
        my_private_key = request.user.private_key
    else:
        my_private_key = create_new_key(request.user, 'private')
    # my_groups = json.dumps(membership.user_groups(request.user.username, full=True))
    # all_groups = json.dumps(membership.all_groups())
    my_groups = []
    all_groups = []
    return render_to_response('users/index.html', {
                                  'all_groups'    : all_groups,
                                  'all_users'     : all_users,
                                  'my_groups'     : my_groups,
                                  'my_private_key': my_private_key,
                                  'my_public_key' : my_public_key,
                                  'user_groups'   : user_groups
                              },
                              RequestContext(request))

@login_required
@user_passes_test(lambda u: u.is_superuser)
def oauth(request):
    """
    Allows users to do oauth management for consumers
    GET all OAuth consumers
    POST to create new consumer with given key, auto-generate / return secret
    """
    try:
        results = {}
        if request.method == 'POST':
            new_key = request.POST['key']
            new_consumer, created = Consumer.objects.get_or_create(key=new_key)
            new_consumer.secret = create_key('private')
            new_consumer.status = 2
            new_consumer.user = request.user
            new_consumer.save()
            results['data'] = extract_oauth_consumers([new_consumer])[0]
        elif request.method == 'GET':
            consumers = Consumer.objects.all()
            results['data'] = extract_oauth_consumers(consumers)
        else:
            raise Exception('Unsupported method!')
    except Exception as ex:
        results = {}
        results['message'] = log_error('users.views.oauth()', ex)
        results['success'] = False
    else:
        results['success'] = True
    finally:
        return HttpResponse(json.dumps(results), content_type='application/json')

@login_required
@user_passes_test(lambda u: u.is_superuser)
def oauth_consumer(request, consumer_id):
    """
    Allows users to do oauth management for a specific consumer
    GET this consumer's name and secret key
    PUT to regenerate the secret key
    DELETE to remove the consumer
    """
    try:
        results = {}
        consumer = Consumer.objects.get(pk=consumer_id)
        if request.method == 'PUT':
            consumer.secret = create_key('private')
            consumer.save()
            results['data'] = extract_oauth_consumers([consumer])[0]
        elif request.method == 'GET':
            results['data'] = extract_oauth_consumers([consumer])[0]
        elif request.method == 'DELETE':
            consumer.delete()
        else:
            raise Exception('Unsupported method!')
    except Exception as ex:
        results = {}
        results['message'] = log_error('users.views.oauth_consumer()', ex)
        results['success'] = False
    else:
        results['success'] = True
    finally:
        return HttpResponse(json.dumps(results), content_type='application/json')

@login_required
@user_passes_test(lambda u: u.is_staff)
def regen_keys(request):
    """
    Requires that users are logged in via Touchstone--only way to get here
    Create new public / private keys for the user. Save them in the
    database and return them to the browser.
    """
    try:
        results = {}
        results['my_public_key'] = create_new_key(request.user, 'public')
        results['my_private_key'] = create_new_key(request.user, 'private')
    except Exception as ex:
        results['message'] = log_error('users.views.regen_keys()', ex)
        results['success'] = False
    else:
        results['success'] = True
    finally:
        return HttpResponse(json.dumps(results), content_type='application/json')

@login_required
@user_passes_test(lambda u: u.is_staff)
def remove(request):
    """
    Remove a user from a specific group with a specific role
    """
    try:
        membership = Membership()
        results = {}
        if request.method == 'POST' and request.user.is_superuser:
            user_to_delete = request.POST.get('username', request.user.username)
            if user_to_delete == '':

templates/users/index.html
<!DOCTYPE html>
<html lang='en' xmlns="http://www.w3.org/1999/xhtml">
<!--
-->
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="MIT Assessment Service">
    <meta name="author" content="MIT ODL">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

    {% load i18n %}
    {% load static %}

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"/>
    <!--Put these jQuery stylesheets here to override the bootstrap ones...
    need to do this so that the search menu results don't get overlaid on top of the input box-->
    <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/jquery.ui/1.10.1/themes/ui-lightness/jquery-ui.min.css"/>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/3.4.6/select2.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/vendor/bootstrap-dialog.css" />

    <link rel="stylesheet" href="{{ STATIC_URL }}css/assessments/style.css" />
    <script data-main="{{ STATIC_URL }}js/main" src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.11/require.min.js"></script>
    <script type="application/javascript">
        var all_groups = "{{ all_groups }}";
        var all_users = "{{ all_users }}";
        var my_groups = "{{ my_groups }}";
        var my_private_key = "{{ my_private_key }}";
        var my_public_key = "{{ my_public_key }}";
        var user_groups = "{{ user_groups }}";
    </script>
    {% block header_script %} {% endblock %}

</head>
<body class="portal">
    {% csrf_token %}
    <div id="navbar_wrapper"></div>
    <div id="container" class="container"></div>
    <div class="row resetSides" id="footer"></div>
</body>
</html>

templates/users/splash.html
<!DOCTYPE html>
<html lang='en' xmlns="http://www.w3.org/1999/xhtml">
<!--
-->
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Login">
    <meta name="author" content="MIT ODL">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

    {% load i18n %}
    {% load static %}

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"/>
    <!--Put these jQuery stylesheets here to override the bootstrap ones...
    need to do this so that the search menu results don't get overlaid on top of the input box-->
    <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/jquery.ui/1.10.1/themes/ui-lightness/jquery-ui.min.css"/>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"/>

    <link rel="stylesheet" href="{{ STATIC_URL }}css/assessments/style.css" />

</head>
<body class="portal">
    <div id="main" class="container-fluid">
        <div id="header" class="text-center row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 well well-small ">
                <h1 class="">Assessment Service User Management</h1>
            </div>
        </div>
        <div id="tech_warning" class="text-center row">
            <div class="col-lg-offset-4 col-md-offset-4 col-sm-12 col-xs-12 col-md-4 col-lg-4">
                <p class="text_bold red">Please note that this website is only compatible with the latest versions of FF / Chrome / Safari on Mac OS or FF / Chrome on Windows. It has not been tested on other combinations.
                </p>
            </div>
        </div>
        <div id="login_container" class="row">
            <div id="email_div" class="box">
                <div class="row reset_left text-center">
                    <form action="{% url 'users:login' %}" method="POST" enctype="multipart/form-data" class="form-signin">
                        {% csrf_token %}
                        <h2 class="form-signin-heading" id="login_heading">Login</h2>
                        <input type="text" class="input-block-level" name="username" placeholder="E-mail">
                        <input type="password" class="input-block-level" name="password" placeholder="Password">
                        <input type="hidden" name="next" value="{{ next }}"/>
                        <button id="login" class="btn btn-large btn-primary" type="submit">Sign in</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div id="status" class="">
    </div>
    <div class="container-fluid">
        <div class="row text-center">
            <div class="offset4 span4">
                <p class="logintxt red"> {{ state }} </p>
            </div>
        </div>
    </div>
    <div id="footer" class="container-fluid">
        <div class="row text-center">
            <div class="offset4 span4">
              <p>Application development and website support provided by</p>
              <p>the <a href="http://odl.mit.edu">MIT Office of Digital Learning (ODL).</a></p>
            </div>
        </div>
    </div>
</body>
</html>